name: hetu_script
description: Hetu is a lightweight script language written in Dart for embedding in Flutter apps.
version: 0.1.0
homepage: https://github.com/hetu-script/hetu-script
publish_to: https://pub.dartlang.org

executables:
  hetu: repl

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
