name: hetu_script
description: Hetu is a lightweight script language written in Dart. Its interpreter is intended to be embedded in Dart programs.
version: 0.0.2
homepage: https://github.com/hythl0day/hetu_script

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
